version: '3'

services:
  app:
    build: .
    entrypoint: dockerize -wait tcp://postgres:5432 timeout 20s ./.docker/entrypoint.sh
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
    depends_on:
      - postgres
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  postgres:
    build: ./.docker/postgresql
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql
    environment:
      - POSTGRES_USER=fin
      - POSTGRES_ROOT_PASSWORD=root
